project:
  type: website
  output-dir: docs

website:
  title: "Maria Mangru"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: writings.qmd
        text: Writing Samples
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



